export enum EventType {
  CREATE_SHAPE = "CREATE_SHAPE",
  CREATE_SQUARE_PROMPT = "CREATE_SQUARE_PROMPT",
  ADD_SQUARE = "ADD_SQUARE",
  SET_STATE = "SET_STATE",
  PROMPT_CREATE_CHARACTER = "PROMPT_CREATE_CHARACTER",
}
